// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwhAK6Zt9OCU_0BPXTdr3uhNhXCrH9y3U',
    appId: '1:1036584065214:android:b100ba9a6d519b81a266ef',
    messagingSenderId: '1036584065214',
    projectId: 'vibora-event-app',
    databaseURL: 'https://vibora-event-app-default-rtdb.firebaseio.com',
    storageBucket: 'vibora-event-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbgASFS4BA2su1mJkFirE1pmp9lM02DEU',
    appId: '1:1036584065214:ios:56f2a6f4099cdf22a266ef',
    messagingSenderId: '1036584065214',
    projectId: 'vibora-event-app',
    databaseURL: 'https://vibora-event-app-default-rtdb.firebaseio.com',
    storageBucket: 'vibora-event-app.firebasestorage.app',
    iosBundleId: 'com.eventconnect.eventConnect',
  );

}